steps:
  - script: |
      sudo cp .azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
      sudo chmod +x /etc/init.d/xvfb
      sudo update-rc.d xvfb defaults
      sudo service xvfb start
    displayName: "Start X Virtual Frame Buffer"
    condition: eq(variables['Agent.OS'], 'Linux')

  - task: Npm@1
    displayName: "Test"
    timeoutInMinutes: 10
    inputs:
      command: custom
      customCommand: test
    env:
      SERVICE_PRINCIPAL_CLIENT_ID: $(SERVICE_PRINCIPAL_CLIENT_ID)
      SERVICE_PRINCIPAL_SECRET: $(SERVICE_PRINCIPAL_SECRET)
      SERVICE_PRINCIPAL_DOMAIN: $(SERVICE_PRINCIPAL_DOMAIN)
      DISPLAY: :10 # Only necessary for linux tests
      LANGSERVER_NUGET_USERNAME: $(LANGSERVER_NUGET_USERNAME)
      LANGSERVER_NUGET_PASSWORD: $(LANGSERVER_NUGET_PASSWORD)
      DISABLE_LANGUAGE_SERVER: ${{variables['System.PullRequest.IsFork']}}

  - task: PublishTestResults@2
    displayName: "Publish Test Results"
    inputs:
      testResultsFiles: "*-results.xml"
      testRunTitle: "$(Agent.OS)"
    condition: succeededOrFailed()
